ershou/apps/df_goods/urls.py
from django.conf.urls import url,re_path
from django.views.static import serve
from tiaozao_shop import settings
from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^index/$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^detail/(\d+)/$', views.detail, name="detail"),
    url('^content/(\d+)/(\d+)/$', views.content, name="content"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
    re_path('^media/(?P<path>.*)/$',serve,{'document_root':settings.MEDIA_ROOT}),
]

ershou/apps/df_user/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url,re_path
from django.views.static import serve
from tiaozao_shop import settings
from .views import *
from . import viewsUtil

app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),
    url(r'^order/(\d+)$', order, name="order"),
    url(r'^site/$', site, name="site"),
    url(r'^publishers/$',publishers,name="publishers"),
    url(r'^changeInformation/$',changeInformation,name="changeInformation"),
    url(r'^check_user/$',check_user,name="check_user"),
    url('^myself_information/$', myself_information, name="myself_information"),
    url('^shoper_information/(.+)/$', shoper_information, name="shoper_information"),
    url('^message/$', message, name="message"),
    url('^person_message/$', person_message, name="person_message"),
    #url(r'^kefu_message/$', kefu_message, name="kefu_message"),
    url(r'^logout/$', logout, name="logout"),
    #显示验证码
    url(r'^verify_show/$', verify_show,name="verify_show"),
    url(r'^verifycode/$', viewsUtil.verify_code,name="verifycode"),
    #修改密码
    url(r'^changeInPwd/$', changeInPwd,name="changeInPwd"),
    #重置密码
    url(r'^findpwdView/$', findpwdView,name="findpwdView"),
    #退货
    url(r'^tuihuo/$', tuihuo,name="tuihuo"),
    re_path('^media/(?P<path>.*)/$',serve,{'document_root':settings.MEDIA_ROOT}),
]

ershou/ershou/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve  # 上传文件处理函数

from .settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置confurl
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT})
]

ershou/apps/df_goods/models.py
from datetime import datetime

from django.db import models
from tinymce.models import HTMLField  # 使用富文本编辑框要在settings文件中安装
# 将一对多的关系维护在GoodsInfo中维护，另外商品信息与分类信息都属于重要信息需要使用逻辑删除


class TypeInfo(models.Model):
    # 商品分类信息  水果 海鲜等
    isDelete = models.BooleanField(default=False)
    ttitle = models.CharField(max_length=20, verbose_name="分类")

    class Meta:
        verbose_name = "商品类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ttitle


class GoodsInfo(models.Model):
    # 具体商品信息
    isDelete = models.BooleanField(default=False)  # 逻辑删除
    gtitle = models.CharField(max_length=20, verbose_name="商品名称", unique=True)
    gpic = models.ImageField(verbose_name='商品图片', upload_to='df_goods/image/%Y/%m', null=True, blank=True)  # 商品图片
    # gpic = models.ImageField(upload_to="df_goods/image/%Y/%m", verbose_name="图片路径", default="image/default.png")
    gprice = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="商品价格")  # 商品价格小数位为两位，整数位为3位
    gunit = models.CharField(max_length=20,verbose_name="卖家昵称")
    gclick = models.IntegerField(verbose_name="点击量", default=0, null=False)
    #guser=models.CharField(max_length=20, verbose_name="卖家昵称", unique=True)
    gjianjie = models.CharField(max_length=200, verbose_name="简介")
    gkucun = models.IntegerField(verbose_name="库存", default=0)
    gcontent = HTMLField(max_length=200, verbose_name="详情")
    gtype = models.ForeignKey(TypeInfo, on_delete=models.CASCADE, verbose_name="分类")  # 外键关联TypeInfo表
    # gadv = models.BooleanField(default=False) #商品是否推荐

    class Meta:
        verbose_name = "商品"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.gtitle

class GoodsContent(models.Model):
    # 用户评论
    isDelete = models.BooleanField(default=False)  # 逻辑删除
    ctitle = models.CharField(max_length=20, verbose_name="商品名称")
    cpic = models.ImageField(verbose_name='上传图片', upload_to='df_goods/image/%Y/%m', null=True, blank=True)  # 商品图片
    cusername = models.CharField(max_length=20, verbose_name="买家昵称")
    clogo = models.CharField(verbose_name='买家头像',max_length=200,default=None)
    cuser_content = HTMLField(max_length=200, verbose_name="用户评论")
    date_publish = models.DateTimeField(verbose_name="发表时间",default=datetime.now)
    cgoodsname = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name="外键商品")  # 外键关联GoodsInfo表

    class Meta:
        verbose_name = "商品评论"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ctitle
class ContentChart(models.Model):
    # 评论回复
    isDelete = models.BooleanField(default=False)  # 逻辑删除
    ctitle = models.CharField(max_length=20, verbose_name="商品名称")
    cusername = models.CharField(max_length=20, verbose_name="评论者昵称")
    cusername1 = models.CharField(max_length=20, verbose_name="回复者昵称")
    ccontent_chart = HTMLField(max_length=200, verbose_name="评论回复")
    date_publish = models.DateTimeField(verbose_name="发表时间",default=datetime.now)
    ccontent = models.ForeignKey(GoodsContent, on_delete=models.CASCADE, verbose_name="评论id")  # 外键关联GoodsContent表

    class Meta:
        verbose_name = "评论回复"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ctitle

ershou/apps/df_goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from df_user import user_decorator
from df_user.models import UserInfo,Information
from .models import GoodsInfo, TypeInfo,GoodsContent,ContentChart
from df_cart.models import CartInfo
from df_order.models import OrderDetailInfo
from df_user.models import GoodsBrowser
from datetime import datetime
from django.contrib import messages


def index(request):
    # 查询各个分类的最新4条，最热4条数据
    username = request.session.get('user_name')
    user = UserInfo.objects.filter(uname=username).first()
    # 联系客服
    # 展示消息
    username1 = "customer"
    informations = Information.objects.filter()
    #判断用户是否给客服发过信息
    informations1=Information.objects.filter(cusername1=username,cusername=username1)
    import datetime
    nowTime = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')  # 现在
    # 消息回复
    user_name = UserInfo.objects.get(uname=username1)  # 获取当前消息用户信息
    # 展示回复消息
    # persons1=Information.objects.filter(cusername=cusername).values('cusername1').distinct().order_by('cusername1')
    if request.method == "POST":
        cusername = user.uname
        cusername1 = user_name.uname
        ccontent_chart = request.POST.get('title')
        cinformation_id = user_name.id
        if ccontent_chart == "":
            messages.success(request, "请输入内容！")
        else:
            Information.objects.create(cusername=cusername, cusername1=cusername1,
                                       ccontent_chart=ccontent_chart, cinformation_id=cinformation_id)
            messages.success(request, "消息发送成功")
            return redirect(reverse("df_goods:index"))
    typelist = TypeInfo.objects.all()
    #  _set 连表操作
    type0 = typelist[0].goodsinfo_set.order_by('-id')[0:4]  # 按照上传顺序
    type01 = typelist[0].goodsinfo_set.order_by('-gclick')[0:4]  # 按照点击量
    type1 = typelist[1].goodsinfo_set.order_by('-id')[0:4]
    type11 = typelist[1].goodsinfo_set.order_by('-gclick')[0:4]
    type2 = typelist[2].goodsinfo_set.order_by('-id')[0:4]
    type21 = typelist[2].goodsinfo_set.order_by('-gclick')[0:4]
    type3 = typelist[3].goodsinfo_set.order_by('-id')[0:4]
    type31 = typelist[3].goodsinfo_set.order_by('-gclick')[0:4]
    type4 = typelist[4].goodsinfo_set.order_by('-id')[0:4]
    type41 = typelist[4].goodsinfo_set.order_by('-gclick')[0:4]
    type5 = typelist[5].goodsinfo_set.order_by('-id')[0:4]
    type51 = typelist[5].goodsinfo_set.order_by('-gclick')[0:4]

    cart_num = 0
    # 判断是否存在登录状态
    # if request.session.has_key('user_id'):
    if 'user_id' in request.session:
        user_id = request.session['user_id']
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    context = {
        'title': '首页',
        'cart_num': cart_num,
        'guest_cart': 1,
        'type0': type0, 'type01': type01,
        'type1': type1, 'type11': type11,
        'type2': type2, 'type21': type21,
        'type3': type3, 'type31': type31,
        'type4': type4, 'type41': type41,
        'type5': type5, 'type51': type51,
        'user':user,
        'informations': informations,
        'informations1':informations1,
        'username1': username1,
        'user_name': user_name,
        'nowTime':nowTime,
    }

    return render(request, 'df_goods/index.html', context)


def good_list(request, tid, pindex, sort):
    username = request.session.get('user_name')
    user = UserInfo.objects.filter(uname=username).first()
    # tid：商品种类信息  pindex：商品页码 sort：商品显示分类方式
    typeinfo = TypeInfo.objects.get(pk=int(tid))

    # 根据主键查找当前的商品分类
    news = typeinfo.goodsinfo_set.order_by('-id')[0:2]
    # list.html左侧最新商品推荐
    goods_list = []
    # list中间栏商品显示方式
    cart_num, guest_cart = 0, 0

    try:
        user_id = request.session['user_id']
    except:
        user_id = None
    if user_id:
        guest_cart = 1
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    if sort == '1':  # 默认最新
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-id')
    elif sort == '2':  # 按照价格
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-gprice')
    elif sort == '3':  # 按照人气点击量
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-gclick')

    # 创建Paginator一个分页对象
    paginator = Paginator(goods_list, 4)
    # 返回Page对象，包含商品信息
    page = paginator.page(int(pindex))
    context = {
        'title': '商品列表',
        'guest_cart': guest_cart,
        'cart_num': cart_num,
        'page': page,
        'paginator': paginator,
        'typeinfo': typeinfo,
        'sort': sort,  # 排序方式
        'news': news,
        'user': user,
    }
    return render(request, 'df_goods/list.html', context)


def detail(request, gid):
    if 'user_id' in request.session:
        uid = request.session['user_id']
        user = UserInfo.objects.get(id=uid)
        good_id = gid
        goods = GoodsInfo.objects.get(pk=int(good_id))
        goods.gclick = goods.gclick + 1  # 商品点击量
        goods.save()

        news = goods.gtype.goodsinfo_set.order_by('-id')[0:2]
        context = {
            'title': goods.gtype.ttitle,
            'guest_cart': 1,
            'cart_num': cart_count(request),
            'goods': goods,
            'news': news,
            'id': good_id,
            'user': user,
        }
        response = render(request, 'df_goods/detail.html', context)

        try:
            browsed_good = GoodsBrowser.objects.get(user_id=int(uid), good_id=int(good_id))
        except Exception:
            browsed_good = None
        if browsed_good:
            from datetime import datetime
            browsed_good.browser_time = datetime.now()
            browsed_good.save()
        else:
            GoodsBrowser.objects.create(user_id=int(uid), good_id=int(good_id))
            browsed_goods = GoodsBrowser.objects.filter(user_id=int(uid))
            browsed_good_count = browsed_goods.count()
            if browsed_good_count > 5:
                ordered_goods = browsed_goods.order_by("-browser_time")
                for _ in ordered_goods[5:]:
                    _.delete()
        return response

    else:
        good_id = gid
        goods = GoodsInfo.objects.get(pk=int(good_id))
        news = goods.gtype.goodsinfo_set.order_by('-id')[0:2]
        context = {
            'title': goods.gtype.ttitle,
            'guest_cart': 0,
            'cart_num': cart_count(request),
            'goods': goods,
            'news': news,
            'id': good_id,
        }
        return render(request, 'df_goods/detail.html', context)


#评论
def content(request, gid,pindex):
    if 'user_id' in request.session:
        uid = request.session['user_id']
        user = UserInfo.objects.get(id=uid)
        good_id = gid
        goods = GoodsInfo.objects.get(pk=int(good_id))
        #获取当前货物信息
        news = goods.gtype.goodsinfo_set.order_by('-id')[0:2]
        #条件查询
        goodsContents = GoodsContent.objects.filter(cgoodsname_id=good_id).order_by('-date_publish')

        print("当前商品评论数：")
        print(goodsContents.count())
        #订单信息
        goodsOrderDetailInfos=OrderDetailInfo.objects.filter()
        # for goodsOrderDetailInfo in goodsOrderDetailInfos:
        #     if goodsOrderDetailInfo.username == user.uname and goodsOrderDetailInfo.goods_id == goods.id:
        #         xinxi="买过"
        #     else:
        #         xinxi=""
        # 创建Paginator一个分页对象
        paginator = Paginator(goodsContents, 2)
        # 返回Page对象，包含商品信息
        page = paginator.page(int(pindex))
        for goodsContent in page:
            if goodsContent.cgoodsname_id == goods.id:
                content_id=goodsContent.id

        context = {
            'title': goods.gtype.ttitle,
            'guest_cart': 1,
            'cart_num': cart_count(request),
            'goods': goods,
            'id': good_id,
            'news': news,
            'user': user,
            'goodsContents': goodsContents,
            'paginator':paginator,
            'page':page,
            'goodsOrderDetailInfos':goodsOrderDetailInfos,
            # 'xinxi':xinxi,
        }
        if request.method == "POST":
            ctitle = goods.gtitle
            cpic = request.FILES.get('pic')
            cusername = user.uname
            clogo=user.ulogo
            cuser_content = request.POST.get('text')
            cgoodsname_id = goods.id
            if cpic == "":
                GoodsContent.objects.create(ctitle=ctitle, cusername=cusername, cuser_content=cuser_content,cgoodsname_id=cgoodsname_id, clogo=clogo)
                messages.success(request, "评论成功！")
            else:
                GoodsContent.objects.create(ctitle=ctitle, cpic=cpic, cusername=cusername, cuser_content=cuser_content,cgoodsname_id=cgoodsname_id,clogo=clogo)
                messages.success(request, "评论成功！")

        return render(request, 'df_goods/content.html', context)
    else:
        good_id = gid
        goods = GoodsInfo.objects.get(pk=int(good_id))
        # 获取当前货物信息
        news = goods.gtype.goodsinfo_set.order_by('-id')[0:2]
        # 条件查询
        goodsContents = GoodsContent.objects.filter(cgoodsname_id=good_id).order_by('-date_publish')

        print("当前商品评论数：")
        print(goodsContents.count())
        # 订单信息
        goodsOrderDetailInfos = OrderDetailInfo.objects.filter()
        # for goodsOrderDetailInfo in goodsOrderDetailInfos:
        #     if goodsOrderDetailInfo.username == user.uname and goodsOrderDetailInfo.goods_id == goods.id:
        #         xinxi="买过"
        #     else:
        #         xinxi=""
        # 创建Paginator一个分页对象
        paginator = Paginator(goodsContents, 2)
        # 返回Page对象，包含商品信息
        page = paginator.page(int(pindex))
        for goodsContent in page:
            if goodsContent.cgoodsname_id == goods.id:
                content_id = goodsContent.id

        context = {
            'title': goods.gtype.ttitle,

ershou/templates/df_goods/content.html
{% extends 'df_goods/base.html' %}

{% block head %}
    <script type="text/javascript">

{#  通过绑定js事件实现随着商品数量的增长商品总价上涨#}
    function plus() {
        num = parseFloat($('.num_show').val());
        kucun = parseFloat($('.goods_kucun').html());
        if(num<=kucun){
            $('.num_show').val(num+1);
            $('.num_show').blur();
        }
    }

    function minus() {
        num = parseFloat($('.num_show').val());
        if(num>1)
        {
            $('.num_show').val(num-1);
            $('.num_show').blur();
        }
        else {
            {#商品的数量不可以小于1#}
        }
    }

    $(function () {
        $('.num_show').blur(function () {

        num = parseInt($('.num_show').val());

        if(num<=1)
             num = 1;

         kucun = parseInt($('.goods_kucun').text());

         if(num>=kucun)
             num = kucun;

         price = parseFloat($('#gprice').text());
         total = num*price;
         $('.num_show').val(num);
         $('#gtotal').text(total.toFixed(2)+'元');

{#             $('add_cart').attr('href', '/cart/add'+$('gid').val())#}
        });
    });
    </script>

{% endblock head %}

{% block center_content %}
{#  回复评论  #}
<div class="shadow clearfix" id="shadow">
    <div class="close clearfix">
        <div class="model clearfix">
          <form action="" id="formDetil" class="easyui-form"   method="POST" >
              {% csrf_token %}
                    <div  class="table-responsive" style="padding-left: 20%">
                        <tr>
                            <td style="border: none; padding-left: 0;">
                                <img style="width: 100px;height: 100px;border-radius: 50%;overflow: hidden;object-fit: cover;" src="{{ MEDIA_URL }}{{ Content.clogo }}" alt=" " class="img-responsive" />
                            </td><br /><br />
                            <td style="border: none;padding-left: 20px;">
                                用户名：{{Content.cusername}}
                            </td><br /><br />
                            <td style="border: none; padding-left: 10px;">
                                用户评论：<p>{{Content.cuser_content}}</p>
                            </td><br /><br />
                            <td style="border: none; padding-left: 10px;">
                                <textarea type="text" name="text" style="width: 300px;height:200px;" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '你的回复...';}" required="">你的回复...</textarea>
                            </td><br /><br />
                        </tr>
                        <input type="submit" value="提交">
                    </div>
          </form>
        </div>
    </div>
  </div>

{#  回复评论到此为止  #}
	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ goods.gpic }}" style="width: 350px;height: 350px;"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.gtitle }}（卖家昵称：{{ goods.gunit }}）</h3>
			<p>{{ goods.gjianjie }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="gprice">{{ goods.gprice }}</em></span>
				<span class="show_unit">库  存：<span class="goods_kucun">{{ goods.gkucun }}</span></span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:plus();" class="add fr">+</a>
					<a href="javascript:minus();" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em id="gtotal">{{ goods.gprice }}元</em></div>
			<div class="operate_btn">
                {% if request.session.user_name|default:'' != '' %}
                    <a href="javascript:;" class="buy_btn" id="buy_now">立即购买</a>
                {% else %}
                    <a href="{% url "df_user:login" %}" class="buy_btn">立即购买</a>
                {% endif %}
                {% if request.session.user_name|default:'' != '' %}
                    <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
                {% else %}
                    <a href="{% url "df_user:login" %}" class="add_cart" id="add_cart">加入购物车</a>
                {% endif %}
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for goods in news %}
					<li>
						<a href="/detail/{{ goods.id }}"><img src="{{ MEDIA_URL }}{{ goods.gpic }}"></a>
						<h4><a href="/detail/{{ goods.id }}">{{ goods.gtitle }}</a></h4>
						<div class="prize">￥{{ goods.gprice }}</div>
					</li>
                    {%  endfor %}
                </ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="detail_tab_content"><a href="/detail/{{ goods.id }}/">商品介绍</a></li>
				<li class="active">评论</li>
			</ul>

			<div class="tab_content">
				<div role="tabpanel" class="tab-pane fade bootstrap-tab-text" id="profile" aria-labelledby="profile-tab">
								<div class="bootstrap-tab-text-grids">
									{% for goodsContent in page %}
                                            <div class="bootstrap-tab-text-grid">
                                                <div class="bootstrap-tab-text-grid-left">
                                                    <a href="/user/shoper_information/{{ goodsContent.cusername }}/"><img style="width: 100px;height: 100px;border-radius: 50%;overflow: hidden;object-fit: cover;" src="{{ MEDIA_URL }}{{ goodsContent.clogo }}" alt=" " class="img-responsive" /></a>
                                                </div>
                                                <div class="bootstrap-tab-text-grid-right">
                                                    <ul>
                                                        <li><a href="/shoper_information/{{ goodsContent.cusername }}/">{{goodsContent.cusername}}</a></li>
                                                        <li><a href="javascript:void(0)" onclick="quote_comment('${goodsContent}')" class="btn"><span class="glyphicon glyphicon-share" aria-hidden="true"></span>{{goodsContent.date_publish}}</a></li>
                                                    </ul>
                                                    <p>
                                                        {{goodsContent.cuser_content}}
                                                        {% if goodsContent.cpic == "" %}
                                                            (未上传图片)
                                                        {% else %}
                                                            <img style="width: 100px;height: 100px;overflow: hidden;object-fit: cover;" src="{{ MEDIA_URL }}{{ goodsContent.cpic }}" alt=" " class="img-responsive" />
                                                        {% endif %}
                                                    </p>
                                                </div>
                                                <div class="clearfix">
                                                </div>
                                            </div>
                                    {% endfor %}
                                    {% if goodsContents.count == 0 %}
                                        <div class="bootstrap-tab-text-grid">
                                                <p>暂无评论</p>
                                            </div>
                                    {% endif %}
                            {#      分页显示      #}
            <div class="pagenation">
{#                判断是否是第一页#}
                {% if page.has_previous %}
                    <a href="/content/{{ goods.id }}/{{ page.previous_page_number }}">上一页</a>
                {% endif %}

                {% for pindex in paginator.page_range %}
                    {% if pindex == page.number %}
                        <a href="/content/{{ goods.id }}/{{ pindex }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="/content/{{ goods.id }}/{{ pindex }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}

{#                是否为第二页#}
                {% if page.has_next %}
				<a href="/content/{{ goods.id }}/{{ page.next_page_number }}">下一页></a>
                {% endif %}
			</div>
                                {% for goodsOrderDetailInfo in goodsOrderDetailInfos %}
                                    {% if goodsOrderDetailInfo.username == user.uname and goodsOrderDetailInfo.goods_id == goods.id  %}
									<div class="add-review">
										<h4>评论一下</h4>
										<form action="{% url "df_goods:content" goods.id 1 %}" method="post" enctype="multipart/form-data">
{#                                        <form action="{% url "df_goods:content" goods.id pindex %}" method="post" enctype="multipart/form-data">#}
											{% csrf_token %}
                                            <label>上传图片</label><input type="file" name="pic">
                                            <textarea type="text" name="text" required="">Message...</textarea>
{#											<input type="submit" value="提交" id="name" οnblur="checkName()">#}
                                            <input type="submit" value="提交">
										</form>
									</div>
                                    {% endif %}
                                {% endfor %}
								</div>
				</div>
			</div>

		</div>
	</div>

	<div class="add_jump"></div>

	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
    $(document).ready(function(){

        $(".buy_btn").click(function () {
            num = parseInt($('.num_show').val());
            $.get('/cart/add{{ goods.id }}_'+num+'/',function (data) {
                $('#show_count').text(data.count);
            });
            location.href = "/cart/";

        });

        $('#add_cart').click(function() {

            var $add_x = $('#add_cart').offset().top;
            var $add_y = $('#add_cart').offset().left;

            var $to_x = $('#show_count').offset().top;
            var $to_y = $('#show_count').offset().left;

            $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});

            $('#add_cart').click(function() {

    {#            		    先判断是否登录#}
                if ($('.login_btn').text().indexOf('登录') >= 0) {
                    alert('请登陆后购买');
                    location.href('/user/login/');
                    return;
                }

    {#                        购物车添加动画#}
                $(".add_jump").stop().animate({
                        'left': $to_y + 7,
                        'top': $to_x + 7
                    },
                    "fast", function () {
                        $(".add_jump").fadeOut('fast', function () {
                            count = $('.num_show').val();
                            $('#show_count').html(count);
                    });
                });

                num = parseInt($('.num_show').val());
                $.get('/cart/add{{ goods.id }}_'+num+'/',function (data) {
                    $('#show_count').text(data.count);
                });
            });
        });

    });
    </script>
    {#回复评论js#}
<script type="text/javascript">
    let btn = document.getElementsByClassName('btn');
    let shadow = document.getElementById('shadow');
    for (var i = 0, len = btn.length; i < len; i++) {
        btn[i].addEventListener('click', function (e) {
            shadow.className = 'shadow show';
            return false
        }, false);
        shadow.addEventListener('click', function(e) {
          let target = e.target;
          let _class = target.className;
          if(_class.includes('shadow') || _class.includes('close')) {
            shadow.className = 'shadow'
          }
          return false
         }, false);
    }
</script>
{#  弹窗提示  #}
    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}
{% endblock center_content %}